spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poker?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    password: root
    username: 123456